version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:20

jobs:
  build:
    docker:
      - image: circleci/node:20
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 # Ensures that Docker is available
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Docker image with Dockerfile.dev
          command: docker build -t ghana79879/react-test -f Dockerfile.dev .
      - run:
          name: Run tests inside Docker container
          command: docker run -e CI=true ghana79879/react-test npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
